ROOTDIR?=../..

TARGET := stencil_h


USER_MAIN_FILE := himeno.c
USER_CUDA_FILES := himeno.cuda.cu
#USER_FILES := $(YACC_TAB_C) $(LEX_YY_C) 
#USER_H_FILES := $(YACC_TAB_H)
compiler := 0
useCuda := 1


include ../../Makefile

