# Copyright (C) 2009-2010 the North Carolina State University
#  This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

ROOTDIR := ..

TARGET := $(ROOTDIR)/bin/unittest_all

USER_MAIN_FILE := all.cpp
USER_CUDA_FILES := all.cu
USER_H_FILES := BlockSortTest.cpp HiArrayTest.cpp PartitionTest.cpp
#USER_CUDA_FILES := all.cu

UNIT_TEST=1
compiler := 0
useCuda := 1

include ../Makefile