ROOTDIR?=../..

TARGET := matrixMul_h


USER_MAIN_FILE := main.cpp
USER_CUDA_FILES := matrixMul.cu
USER_H_FILES := matrixMul_kernel.cu matrixMul.h
#USER_FILES := $(YACC_TAB_C) $(LEX_YY_C) 
#USER_H_FILES := $(YACC_TAB_H)
compiler := 0
useCuda := 1


include ../../Makefile

