ROOTDIR?=../..

TARGET := bitonic_h


USER_MAIN_FILE := main.cpp
USER_CUDA_FILES := bitonic.cu
#USER_FILES := $(YACC_TAB_C) $(LEX_YY_C) 
USER_H_FILES := bitonic_kernel.cu
compiler := 0
useCuda := 1


include ../../Makefile

